let carte;

carte=["XXXXXXXXXXXXXXXXX",
    "XFOOOOXOOOXOOOOOX",
    "XOXXXOXOXOXOXXXOX",
    "XOXOOOXOXOXOOOXOX",
    "XOXOXOXOXOXOXOXOX",
    "XOXOXOXOXOXOXOXOX",
    "XOXOXOOOOOOOXOXOX",
    "XOOOOOXXXXXOOOOOX",
    "XXXXXOOOPOOOXXXXX",
    "XOOOOOXXXXXOOOOOX",
    "XOXOXOOOOOOOXOXOX",
    "XOXOXOXOXOXOXOXOX",
    "XOXOXOXOXOXOXOXOX",
    "XOXOOOXOXOXOOOXOX",
    "XOXXXOXOXOXOXXXOX",
    "XFOOOOXOOOXOOOOOX",
    "XXXXXXXXXXXXXXXXX"] ;